---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-database
  namespace: default
spec:
  encryptedData:
    dbpassword: AgCvY1Oy9OowKY6S4tAXK9Ozr692kc8JBA0SSzMPcAOwb0wK9TFVkcmMfQji9/mHbVIZCGC2mIeTzqmthWLWcql3JnLW4JAf3mBFNOIyNG2YFryjdrPaOdOW7AWH6Oeip1ZQm6qwedDNt9JXMVwscUs8ni8Bk7SMQi/70kGGy52c278Z7ztGDcImIlyTZEClAVr1UoTQdzHiVWr8MWrkDI6ZpNfHNx3P5fXgokBcLHPGIbtQ+IzP+S2fH6Jc2qP+yvkJEpduXPehazJ7yXbUh4xLJHV+0R42wELV9czp+6Zlh2okX/MwNF9tEMK86TNe9GEGy19ioBogmD8rw1r7MEzsM014XgzgknzXNgrLsZEY7ghYnja7XBNionmKs50CIXKUCVDN0ZGblVQZ2y0/cwztlEqD8Q3BidJn8OHyqG3JOE8YkK4yFvH4QpSv5r4LgMaLHrh7sJbZjywMb+l5AQ3SFEHj3b//qPKBcoY5pR5dztFe8qMr4adkpIs7WlP2K5aR3Wrl3WyvTaNNGjsWkoGrkpvDUgIJeeGeUrOCyUnPp1i1oZunBdRhRxt94c5nvSS+Xa9nw7vKgp0GV+9UFv8BY8EXe1PcdM5Yp8CoiMPSZkzqYhbGY55OA+nd2ZE7lAYbbxcxurOsJOtq8oL5C5Unhh43B9zV6GWkwsdyvwrZH15bj/HLHMpMkNC2eiI17aKSNuKgfB4=
    rootpassword: AgAXmHwmZaEI2BMn12itlAMojEn3Ks3l4U5JJj1vi2AR8uQuE4JXusmrwtNW9pY7TZifPCSd+lyfJ+CNCtEKeyqupmPJTAi0HBnFB3F+TA27b8Lm0wdGXaoRHsh6Q2eSvgspiNgRHG415JcGctXyjLCYx67v2wt4sP4HxnZ4xRrW+TuJfI9FkySRLLuAhIvH/DAOtJ5LpqXg0aD5E+482X8aWMQ48E2k9UVTOvyL4OAi4iKFage3XcRG17aST9VRaEmd2VPNeZHQX7yobIx/8Z/z1Ir3BVhqis3/kT8ccHHH/7Y4najbACKBWTPdIKNCQd0Xb9u1XhHbw+ztw9n7x2wwhRrNKoR5HgtpdT0rpiArgNXcW/q9aEb+hXRtrCLA19M8pq7wOobRgzEYINgEiItIYPcJ6Lfsw+TFVIsZB3h6EqwpvD2QhVr4yV2DHyD7+2D1zLa/xz7LjJBv/WsMTarHG2M1yr6ZdDJBl27f8jjLEZNgBV6ZvfeoRUpQATpoU+OnrevNzcaC2tuJX7UjfWZDg/GeXqGraOP9SQmNWP8JE1SyGEXeeX4w3SiE/09gHR9x/LU5ehruNFo88WR+PZW5WcJNoI4yCRi/ZekXthnxuwh+N0Lt47IM8h1JRBzQQBbLv7Ji/CYZWILRfXWju0XZaqXZe2JVJAB5i95ELbxjM//PhWTlJAg+Gx02bWs+kzHBpEzN
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: app-database
        app.kubernetes.io/version: 1.16.0
        helm.sh/chart: database-0.1.0
      name: app-database
      namespace: default
    type: Opaque
